FE-941: change concept of global thermostat
openmotics/frontend pull request #630
Opened 2021-11-22 14:43 UTC by mremil6

2021-11-23 08:08 UTC, spartanez17 commented
@mremil6 
- You forgot to change thermostat title for Dashboard page
- Thermostat key is missed for menu 
![image](https://user-images.githubusercontent.com/26220556/142989077-3437c9c8-2ef3-4e39-99df-6f03ea72479d.png)

2021-11-23 08:11 UTC, spartanez17 requested changes

2021-11-23 08:11 UTC, spartanez17 commented on src/pages/cloud/thermostats/index.js
> +        console.log(thermostats)
:astonished:

2021-11-23 09:08 UTC, spartanez17 approved these changes

2021-11-26 12:48 UTC, iOlivier commented on src/locales/nl/translation.json
> +            "globalthermostat": "",
```suggestion
            "globalthermostat": "Wijzig alle thermostaten",
```

2021-11-26 12:48 UTC, iOlivier commented on src/locales/nl/translation.json
> +            "thermostats": "",
```suggestion
            "thermostat": "Thermostaat",
            "thermostats": "Thermostaten",
```

2021-11-26 12:49 UTC, iOlivier commented on src/locales/en/translation.json
> +            "globalthermostat": "Change for all thermostats",
```suggestion
            "globalthermostat": "Change all thermostats",
```

2021-11-26 12:54 UTC, iOlivier approved these changes

2021-11-26 12:54 UTC, merged